# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_Form3(object):
    def setupUi(self, UI_Form3):
        UI_Form3.setObjectName("UI_Form3")
        UI_Form3.resize(397, 300)

        self.retranslateUi(UI_Form3)
        QtCore.QMetaObject.connectSlotsByName(UI_Form3)

    def retranslateUi(self, UI_Form3):
        _translate = QtCore.QCoreApplication.translate
        UI_Form3.setWindowTitle(_translate("UI_Form3", "可重复随机数"))
