# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI4.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_Form4(object):
    def setupUi(self, UI_Form4):
        UI_Form4.setObjectName("UI_Form4")
        UI_Form4.resize(400, 300)

        self.retranslateUi(UI_Form4)
        QtCore.QMetaObject.connectSlotsByName(UI_Form4)

    def retranslateUi(self, UI_Form4):
        _translate = QtCore.QCoreApplication.translate
        UI_Form4.setWindowTitle(_translate("UI_Form4", "双重(组)随机数"))
